Acme\DemoBundle\Entity\User:
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            #- Type: Email
        birthday:
            - NotBlank: ~
        shoe_size:
            - NotBlank: ~
            - Range:
                min: 30
                max: 50
        ice_cream:
            - NotBlank: ~
        car:
            - NotBlank: ~
        book:
            - NotBlank: ~
        date:
            - NotBlank: ~
        country:
            - NotBlank: ~
